# version: '3.8'

services:
  # Веб-приложение Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  # Сервис обработки изображений на Celery
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: ["celery", "-A", "project_name", "worker", "--loglevel=info"]
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - rabbitmq
      - db

  # База данных PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Брокер сообщений RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ Management UI

volumes:
  postgres_data:
